// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cladehqfynndkwtumyqy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNsYWRlaHFmeW5uZGt3dHVteXF5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3NzM1NTksImV4cCI6MjA3MTM0OTU1OX0.tvNqfpXiThyFc0xXPLIzGqo9NqC9AALw4NI_O795EaM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});